#!/bin/sh
# abc2svg with raw nodeJS
progdir=`dirname $0`

cat ${progdir}/abc2svg-1.js ${progdir}/cmdline.js > /tmp/toto.js
case $1 in
	*.js)
		cat $1 >> /tmp/toto.js
		shift
		;;
	*)
		cat ${progdir}/toxhtml.js >> /tmp/toto.js
		;;
esac
cat <<EOF >> /tmp/toto.js
    var	progdir='${progdir}/'

function print(str) {
	process.stdout.write(str + '\n')
}

function printErr(str) {
	process.stderr.write(str + '\n')
}

function readFile(fname) {
    var	fs = require("fs");

	return fs.readFileSync(fname).toString()
}

function loadRelativeToScript(script) {
	var geval = eval;
	geval(readFile(progdir + script))
}

function quit() {
	process.exit(1)
}

// main
	var args = process.argv
	if (!args[2]) {
		print("abcnode-" + abc2svg.version + " " + abc2svg.vdate + "\n" +
			"	ABC to SVG translator\n" +
			"	Usage: abcnode [options] ABC_file");
		quit(1)
	}
	args.shift()
	args.shift()
	abc_cmd("abcnode", args)
EOF

node /tmp/toto.js "$@"
