#!/bin/sh
# abc2svg with d8 (libv8 Google)
progdir=`dirname $0`

exec d8 -e "var args='$*', progdir='${progdir}/'

load(progdir + 'abc2svg-1.js');

// interpreter specific functions
abc2svg.print = function(str) {
	print(str)
}
abc2svg.quit = function() {
	quit(1)
}
abc2svg.readFile = function(fname) {
	return read(fname)
}
abc2svg.loadjs = function(fn, relay, onerror) {
	try {
		load(progdir + script)
		if (relay)
			relay()
	} catch(e) {
		if (onerror)
			onerror()
		else
			print('Cannot read file ' + fn)
	}
}

load(progdir + 'cmdline.js')

// main
	args = args.split(/\s+/)
	if (/\.js$/.test(args[0])) {
		load(args[0])
		args.shift()
	}
	if (typeof(abc2svg.abc_init) != 'function')
		load(progdir + 'toxhtml.js')

	if (!args[0]) {
		print('ABC translator with d8 (Google v8 shell)\
 and abc2svg-' + abc2svg.version + ' ' + abc2svg.vdate + '\n\
Usage:\n\
  abcv8 [script.js] [g_options] ABC_file [f_options] [ABC_file [f_options]]*\n\
Arguments:\n\
  script.js  generation script to load - default: toxhtml.js (XHTML+SVG)\n\
  g_options  global ABC options\n\
  ABC_file   ABC file\n\
  f_options  file options')
		quit()
	}
	abc_cmd('abcv8', args)
"
